//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.18444
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace LNDLWcfServiceHost.ServiceReference1 {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ServiceReference1.ILNDLWcfService")]
    public interface ILNDLWcfService {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ILNDLWcfService/GetMessage", ReplyAction="http://tempuri.org/ILNDLWcfService/GetMessageResponse")]
        string GetMessage(string name);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ILNDLWcfService/GetMessage", ReplyAction="http://tempuri.org/ILNDLWcfService/GetMessageResponse")]
        System.Threading.Tasks.Task<string> GetMessageAsync(string name);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ILNDLWcfService/getOrderList", ReplyAction="http://tempuri.org/ILNDLWcfService/getOrderListResponse")]
        LNDLWcfService.OrderEntity[] getOrderList();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ILNDLWcfService/getOrderList", ReplyAction="http://tempuri.org/ILNDLWcfService/getOrderListResponse")]
        System.Threading.Tasks.Task<LNDLWcfService.OrderEntity[]> getOrderListAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ILNDLWcfService/saveOrder", ReplyAction="http://tempuri.org/ILNDLWcfService/saveOrderResponse")]
        void saveOrder(LNDLWcfService.OrderEntity o);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ILNDLWcfService/saveOrder", ReplyAction="http://tempuri.org/ILNDLWcfService/saveOrderResponse")]
        System.Threading.Tasks.Task saveOrderAsync(LNDLWcfService.OrderEntity o);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface ILNDLWcfServiceChannel : LNDLWcfServiceHost.ServiceReference1.ILNDLWcfService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class LNDLWcfServiceClient : System.ServiceModel.ClientBase<LNDLWcfServiceHost.ServiceReference1.ILNDLWcfService>, LNDLWcfServiceHost.ServiceReference1.ILNDLWcfService {
        
        public LNDLWcfServiceClient() {
        }
        
        public LNDLWcfServiceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public LNDLWcfServiceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public LNDLWcfServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public LNDLWcfServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public string GetMessage(string name) {
            return base.Channel.GetMessage(name);
        }
        
        public System.Threading.Tasks.Task<string> GetMessageAsync(string name) {
            return base.Channel.GetMessageAsync(name);
        }
        
        public LNDLWcfService.OrderEntity[] getOrderList() {
            return base.Channel.getOrderList();
        }
        
        public System.Threading.Tasks.Task<LNDLWcfService.OrderEntity[]> getOrderListAsync() {
            return base.Channel.getOrderListAsync();
        }
        
        public void saveOrder(LNDLWcfService.OrderEntity o) {
            base.Channel.saveOrder(o);
        }
        
        public System.Threading.Tasks.Task saveOrderAsync(LNDLWcfService.OrderEntity o) {
            return base.Channel.saveOrderAsync(o);
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ServiceReference1.IWCFUploader")]
    public interface IWCFUploader {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IWCFUploader/Upload", ReplyAction="http://tempuri.org/IWCFUploader/UploadResponse")]
        LNDLWcfService.UploadedFile Upload(System.IO.Stream Uploading);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IWCFUploader/Upload", ReplyAction="http://tempuri.org/IWCFUploader/UploadResponse")]
        System.Threading.Tasks.Task<LNDLWcfService.UploadedFile> UploadAsync(System.IO.Stream Uploading);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IWCFUploader/Transform", ReplyAction="http://tempuri.org/IWCFUploader/TransformResponse")]
        LNDLWcfService.UploadedFile Transform(LNDLWcfService.UploadedFile Uploading, string FileName);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IWCFUploader/Transform", ReplyAction="http://tempuri.org/IWCFUploader/TransformResponse")]
        System.Threading.Tasks.Task<LNDLWcfService.UploadedFile> TransformAsync(LNDLWcfService.UploadedFile Uploading, string FileName);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IWCFUploaderChannel : LNDLWcfServiceHost.ServiceReference1.IWCFUploader, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class WCFUploaderClient : System.ServiceModel.ClientBase<LNDLWcfServiceHost.ServiceReference1.IWCFUploader>, LNDLWcfServiceHost.ServiceReference1.IWCFUploader {
        
        public WCFUploaderClient() {
        }
        
        public WCFUploaderClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public WCFUploaderClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public WCFUploaderClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public WCFUploaderClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public LNDLWcfService.UploadedFile Upload(System.IO.Stream Uploading) {
            return base.Channel.Upload(Uploading);
        }
        
        public System.Threading.Tasks.Task<LNDLWcfService.UploadedFile> UploadAsync(System.IO.Stream Uploading) {
            return base.Channel.UploadAsync(Uploading);
        }
        
        public LNDLWcfService.UploadedFile Transform(LNDLWcfService.UploadedFile Uploading, string FileName) {
            return base.Channel.Transform(Uploading, FileName);
        }
        
        public System.Threading.Tasks.Task<LNDLWcfService.UploadedFile> TransformAsync(LNDLWcfService.UploadedFile Uploading, string FileName) {
            return base.Channel.TransformAsync(Uploading, FileName);
        }
    }
}
