//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成�?
//
//     手动更改此文件可能导致应用程序出现意外的行为�?
//     如果重新生成代码，将覆盖对此文件的手动更改�?
// </auto-generated>
//------------------------------------------------------------------------------

namespace LNDL.EFDAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblUsers
    {
        public int id { get; set; }
        public string name { get; set; }
        public string password { get; set; }
        public string role { get; set; }
        public Nullable<System.DateTime> createDate { get; set; }
        public Nullable<int> logOnTries { get; set; }
        public Nullable<bool> isLocked { get; set; }
        public Nullable<System.DateTime> lockedDate { get; set; }
    }
}
