// <auto-generated />
namespace LNDLWcfService.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.1-30610")]
    public sealed partial class LNDLWcfServiceCodeFirstDALProductContext : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(LNDLWcfServiceCodeFirstDALProductContext));
        
        string IMigrationMetadata.Id
        {
            get { return "201501112005058_LNDLWcfService.CodeFirstDAL.ProductContext"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
