//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace WcfProductService.EFDAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblCurtain
    {
        public int id { get; set; }
        public string name { get; set; }
        public string color { get; set; }
        public Nullable<int> width { get; set; }
        public Nullable<int> length { get; set; }
        public string unit { get; set; }
        public Nullable<bool> FR { get; set; }
        public Nullable<bool> blackout { get; set; }
        public Nullable<bool> grommet { get; set; }
        public Nullable<bool> lining { get; set; }
        public string pattern { get; set; }
        public Nullable<int> piecePerBag { get; set; }
        public Nullable<int> bagPerBox { get; set; }
        public string imageName { get; set; }
        public string generalNote { get; set; }
        public Nullable<decimal> unitPriceIn { get; set; }
        public Nullable<decimal> unitPriceSale1 { get; set; }
        public Nullable<decimal> unitPriceSale2 { get; set; }
        public Nullable<System.DateTime> itemCreateDate { get; set; }
        public Nullable<System.DateTime> itemModifyDate { get; set; }
    }
}
