//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace WcfProductService.EFDAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblFabric
    {
        public int id { get; set; }
        public string name { get; set; }
        public string GSM { get; set; }
        public string color { get; set; }
        public Nullable<int> width { get; set; }
        public string widthUnit { get; set; }
        public Nullable<int> lengthPerRoll { get; set; }
        public string unit { get; set; }
        public Nullable<bool> FR { get; set; }
        public string pattern { get; set; }
        public string imageName { get; set; }
        public string generalNote { get; set; }
    }
}
